Adding options to aatp script: aatp/run -h

diff --git a/aatp/run b/aatp/run
--- a/aatp/run
+++ b/aatp/run
@@ -1,31 +1,62 @@
 #!/usr/bin/env bash
+BUILD=1
 build_n_run() {
-    docker compose -f $1  --project-directory . build
+    if [ $BUILD -eq 1 ]
+    then
+        echo ">>> Building a lab based on $1"
+        docker compose -f $1  --project-directory . build $BUILD_OPTIONS
+        if [ $? -ne 0 ]
+        then
+            exit "docker compose build failed"
+        fi
+    fi
+    echo ">>> Running a lab based on $1"
     docker compose -f $1  --project-directory . up --exit-code-from runner
 }
+usage() {
+   cat <<EOS
+This script builds & runs the acceptance test procedures.
+When no path is given it fnds all the testing suites under `./aatp`
+setup their lab and runs them.
+
+Syntax: $0 [-h|z|n] <test_path>
+options:
+
+h     Print this usage
+z     Build the docker images from scratch before running
+n     Don't build the images
+
+EOS
+}
+
+exit_error() {
+    usage
+    exit 1
+}
+
+while getopts ":hnz" option; do
+    echo "option " $option
+   case $option in
+      h) # display usage
+         usage
+         exit;;
+      n) # No Build
+         BUILD=0
+         ;;
+      z) # No Cache
+         BUILD_OPTIONS="--no-cache"
+         ;;
+      \?) # Invalid option
+         echo "Error: Invalid option"
+         exit_error;;
+   esac
+done
+shift $((OPTIND-1))
 if [ $# -eq 0 ]
 then
-    echo ">>> Starting full AATP <<<"
-    
-    npm run lint
-
-    echo ">>> TODO: finish TypeScript refactor and pass the linter"
-    npx vitest run || exit 1
-    if [ $? -ne 0 ]
-    then
-        echo ">>> unit tests FAILED"
-        exit 2
-    fi
-    npx vite build
-    if [ $? -ne 0 ]
-    then
-        echo ">>> unit tests FAILED"
-        exit 3
-    fi
     for compose in `find aatp -name "lab.yaml"`
     do
         dir=$(dirname $compose)
-        echo ">>> bringing up a lab from $dir"
         build_n_run $compose
         if [ $? -ne 0 ]
         then
@@ -34,10 +65,8 @@ then
         fi
     done
 else
-    npx vite build
     for arg in $@
     do
-        echo ">>> setting up a lab from $arg"
         build_n_run $arg/lab.yaml
         if [ $? -ne 0 ]
         then
